version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: aeris-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: aeris
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: openjdk:17
    container_name: aeris-backend
    volumes:
      - ./target/app.jar:/app/app.jar
    command: [ "java", "-jar", "/app/app.jar" ]
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aeris
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  pgdata: